- id: terraform-conda
  name: terraform-conda
  entry: terraform fmt
  language: conda
  description: Rewrites all Terraform configuration files to a canonical format.
  types: [text]
  require_serial: true
  additional_dependencies: []
